#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MAIN_LAUNCHER="${REPO_DIR}/scripts/launch_featgen_main_pool14_seed5_tmux.sh"

SEEDS_CSV="${SEEDS_CSV:-0}"
TASKS_CSV="${TASKS_CSV:-entity_matching,joinable_table_search,schema_matching,union_table_search}"
DATASETS_CSV="${DATASETS_CSV:-magellan,santos_benchmark,wikidbs}"
GPU_IDS_CSV="${GPU_IDS_CSV:-0,1}"
SESSION_PREFIX="${SESSION_PREFIX:-featgen_nosymbolic_ablation}"

BUILD_CONTEXTS="${BUILD_CONTEXTS:-0}"
CONTEXTS_DIR="${CONTEXTS_DIR:-${REPO_DIR}/outputs/featgen_contexts}"
TOP_ATOMS="${TOP_ATOMS:-8}"
TRAIN_LOG_DIR="${TRAIN_LOG_DIR:-${REPO_DIR}/outputs/tmux_logs/${SESSION_PREFIX}}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${REPO_DIR}/outputs/${SESSION_PREFIX}}"

ATOM_GEN_MODE="${ATOM_GEN_MODE:-real}"
SYMBOLIC_GEN_MODE="${SYMBOLIC_GEN_MODE:-real}"
NUM_GENERATED_FEATURES="${NUM_GENERATED_FEATURES:-auto}"
TARGET_TOTAL_POOL_SIZE="${TARGET_TOTAL_POOL_SIZE:-12}"
NUM_SYMBOLIC_CHANNELS="${NUM_SYMBOLIC_CHANNELS:-auto}"
SYMBOLIC_MIN_CHANNELS="${SYMBOLIC_MIN_CHANNELS:-auto}"
ATOM_MODEL="${ATOM_MODEL:-gpt-5}"
ATOM_BASE_URL="${ATOM_BASE_URL:-}"
ATOM_MAX_REPAIR_ATTEMPTS="${ATOM_MAX_REPAIR_ATTEMPTS:-2}"
ATOM_ALLOW_EXTRA_FEATURES_TRUNCATE="${ATOM_ALLOW_EXTRA_FEATURES_TRUNCATE:-1}"
SYMBOLIC_MODEL="${SYMBOLIC_MODEL:-gpt-5}"
SYMBOLIC_BASE_URL="${SYMBOLIC_BASE_URL:-}"
EPOCHS="${EPOCHS:-1000}"
PATIENCE="${PATIENCE:-20}"
BATCH_SIZE="${BATCH_SIZE:-192}"
GNN_TYPE="${GNN_TYPE:-our}"
NUM_WORKERS="${NUM_WORKERS:-4}"
DEBUG_MAX_TRAIN_EDGES="${DEBUG_MAX_TRAIN_EDGES:-0}"
DEBUG_MAX_VAL_EDGES="${DEBUG_MAX_VAL_EDGES:-0}"
DEBUG_MAX_TEST_EDGES="${DEBUG_MAX_TEST_EDGES:-0}"
EM_PAIR_CACHE_MODE="${EM_PAIR_CACHE_MODE:-readwrite}"
EM_PAIR_CACHE_ROOT_BASE="${EM_PAIR_CACHE_ROOT_BASE:-${REPO_DIR}/outputs/em_pair_cache}"
EM_ROW_STATS_MODE="${EM_ROW_STATS_MODE:-full}"
FORCE_ATOM_REGEN="${FORCE_ATOM_REGEN:-0}"
FORCE_SYMBOLIC_REGEN="${FORCE_SYMBOLIC_REGEN:-0}"
SKIP_TRAIN="${SKIP_TRAIN:-0}"

if [[ ! -x "${MAIN_LAUNCHER}" ]]; then
  echo "[ERROR] main launcher missing: ${MAIN_LAUNCHER}" >&2
  exit 2
fi

echo "[INFO] launching no-symbolic ablation"
echo "[INFO] generated atoms may still be prepared if missing, but they will not be fed into the model"
echo "[INFO] session_prefix=${SESSION_PREFIX}"
echo "[INFO] seeds=${SEEDS_CSV} tasks=${TASKS_CSV} datasets=${DATASETS_CSV} gpus=${GPU_IDS_CSV}"

SEEDS_CSV="${SEEDS_CSV}" \
TASKS_CSV="${TASKS_CSV}" \
DATASETS_CSV="${DATASETS_CSV}" \
GPU_IDS_CSV="${GPU_IDS_CSV}" \
SESSION_PREFIX="${SESSION_PREFIX}" \
BUILD_CONTEXTS="${BUILD_CONTEXTS}" \
CONTEXTS_DIR="${CONTEXTS_DIR}" \
TOP_ATOMS="${TOP_ATOMS}" \
TRAIN_LOG_DIR="${TRAIN_LOG_DIR}" \
ARTIFACT_ROOT="${ARTIFACT_ROOT}" \
ATOM_GEN_MODE="${ATOM_GEN_MODE}" \
SYMBOLIC_GEN_MODE="${SYMBOLIC_GEN_MODE}" \
NUM_GENERATED_FEATURES="${NUM_GENERATED_FEATURES}" \
TARGET_TOTAL_POOL_SIZE="${TARGET_TOTAL_POOL_SIZE}" \
NUM_SYMBOLIC_CHANNELS="${NUM_SYMBOLIC_CHANNELS}" \
SYMBOLIC_MIN_CHANNELS="${SYMBOLIC_MIN_CHANNELS}" \
ATOM_MODEL="${ATOM_MODEL}" \
ATOM_BASE_URL="${ATOM_BASE_URL}" \
ATOM_MAX_REPAIR_ATTEMPTS="${ATOM_MAX_REPAIR_ATTEMPTS}" \
ATOM_ALLOW_EXTRA_FEATURES_TRUNCATE="${ATOM_ALLOW_EXTRA_FEATURES_TRUNCATE}" \
SYMBOLIC_MODEL="${SYMBOLIC_MODEL}" \
SYMBOLIC_BASE_URL="${SYMBOLIC_BASE_URL}" \
EPOCHS="${EPOCHS}" \
PATIENCE="${PATIENCE}" \
BATCH_SIZE="${BATCH_SIZE}" \
GNN_TYPE="${GNN_TYPE}" \
NUM_WORKERS="${NUM_WORKERS}" \
DEBUG_MAX_TRAIN_EDGES="${DEBUG_MAX_TRAIN_EDGES}" \
DEBUG_MAX_VAL_EDGES="${DEBUG_MAX_VAL_EDGES}" \
DEBUG_MAX_TEST_EDGES="${DEBUG_MAX_TEST_EDGES}" \
EM_PAIR_CACHE_MODE="${EM_PAIR_CACHE_MODE}" \
EM_PAIR_CACHE_ROOT_BASE="${EM_PAIR_CACHE_ROOT_BASE}" \
EM_ROW_STATS_MODE="${EM_ROW_STATS_MODE}" \
FORCE_ATOM_REGEN="${FORCE_ATOM_REGEN}" \
FORCE_SYMBOLIC_REGEN="${FORCE_SYMBOLIC_REGEN}" \
ENABLE_SYMBOLIC='0' \
SKIP_TRAIN="${SKIP_TRAIN}" \
bash "${MAIN_LAUNCHER}"
