#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

TASKS_CSV="${TASKS_CSV:-entity_matching,joinable_table_search,schema_matching,union_table_search}"
DATASETS_CSV="${DATASETS_CSV:-magellan,santos_benchmark,wikidbs}"
GPU_IDS_CSV="${GPU_IDS_CSV:-0}"
SESSION_PREFIX="${SESSION_PREFIX:-featgen_gen0428}"
TRAIN_LOG_DIR="${TRAIN_LOG_DIR:-${REPO_DIR}/outputs/tmux_logs/featgen_generation_grid}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${REPO_DIR}/outputs/featgen_generation_grid}"
BUILD_CONTEXTS="${BUILD_CONTEXTS:-1}"

ATOM_GEN_MODE="${ATOM_GEN_MODE:-real}"
SYMBOLIC_GEN_MODE="${SYMBOLIC_GEN_MODE:-real}"
NUM_GENERATED_FEATURES="${NUM_GENERATED_FEATURES:-auto}"
TARGET_TOTAL_POOL_SIZE="${TARGET_TOTAL_POOL_SIZE:-12}"
NUM_SYMBOLIC_CHANNELS="${NUM_SYMBOLIC_CHANNELS:-auto}"
SYMBOLIC_MIN_CHANNELS="${SYMBOLIC_MIN_CHANNELS:-auto}"
ATOM_MODEL="${ATOM_MODEL:-gpt-5}"
SYMBOLIC_MODEL="${SYMBOLIC_MODEL:-gpt-5}"
FORCE_ATOM_REGEN="${FORCE_ATOM_REGEN:-1}"
FORCE_SYMBOLIC_REGEN="${FORCE_SYMBOLIC_REGEN:-1}"
SKIP_TRAIN=1

exec env \
  TASKS_CSV="${TASKS_CSV}" \
  DATASETS_CSV="${DATASETS_CSV}" \
  GPU_IDS_CSV="${GPU_IDS_CSV}" \
  SESSION_PREFIX="${SESSION_PREFIX}" \
  TRAIN_LOG_DIR="${TRAIN_LOG_DIR}" \
  ARTIFACT_ROOT="${ARTIFACT_ROOT}" \
  BUILD_CONTEXTS="${BUILD_CONTEXTS}" \
  ATOM_GEN_MODE="${ATOM_GEN_MODE}" \
  SYMBOLIC_GEN_MODE="${SYMBOLIC_GEN_MODE}" \
  NUM_GENERATED_FEATURES="${NUM_GENERATED_FEATURES}" \
  TARGET_TOTAL_POOL_SIZE="${TARGET_TOTAL_POOL_SIZE}" \
  NUM_SYMBOLIC_CHANNELS="${NUM_SYMBOLIC_CHANNELS}" \
  SYMBOLIC_MIN_CHANNELS="${SYMBOLIC_MIN_CHANNELS}" \
  ATOM_MODEL="${ATOM_MODEL}" \
  SYMBOLIC_MODEL="${SYMBOLIC_MODEL}" \
  FORCE_ATOM_REGEN="${FORCE_ATOM_REGEN}" \
  FORCE_SYMBOLIC_REGEN="${FORCE_SYMBOLIC_REGEN}" \
  SKIP_TRAIN="${SKIP_TRAIN}" \
  "${SCRIPT_DIR}/launch_featgen_grid_tmux.sh"
